site_name: Volumetricspy
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: deep purple
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md

repo_url: https://github.com/scuervo91/Volumetricspy
repo_name: scuervo91/volumetricspy

plugins:
  - search

markdown_extensions:
  - admonition
