name: Python package
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Publish python poetry package
      uses: JRubics/poetry-publish@v1.16
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
